development:
  adapter: mysql2
  database: monsterhunt
  host: localhost
  username: root
  password: root
  encoding: utf8

test:
  adapter: mysql2
  database: monsterhunttest
  host: localhost
  username: root
  password: root
  encoding: utf8

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: monsterhunt_prod
  username: monsterhunt
  password: <%= ENV['MONSTERHUNT_DATABASE_PASSWORD'] %>