development:
  adapter: mysql2
  database: monsterhunt
  host: localhost
  username: root
  password: root
  encoding: utf8

test:
  adapter: mysql2
  database: monsterhunttest
  host: localhost
  username: root
  password: root
  encoding: utf8